### ISSUE TITLE
Adding uint64_t and int64_t to supported primitive spinel types

### ISSUE THREAD

**Issue by abtink** [openthread/spinel-spec#6]
Spinel specification supports 8,16,32-bit long singed/unsigned integer as primitive types.  While `uint64_t` not used often, adding `uint64_t` can be useful for certain situations (e.g., timestamps in Thread operational dataset are `uint64_t`).

Using `x`/`X` (for `int64_t`/`uint64_t`) for the encoding char string (?)

Thoughts?

**Comment by darconeous** [comment]
Well, the data type notation has been removed form the Spinel spec, replaced with more IETF-like diagrams. Feel free to add it to spinel.c/spinel.h.

**Comment by abtink** [comment]
Added support for this in PR: https://github.com/openthread/openthread/pull/2309.
